### ISSUE TITLE
bad db code ;)

### ISSUE THREAD

**Issue by vitaly-t** [Kalita-Roman/brest-cadastral-map#1]
from here: https://github.com/Kalita-Roman/brest-cadastral-map/blob/40c7d59889ff22f877072d275568b5b88b6e95ef/database/db.js#L16

The reason why: [Tasks versus root/direct queries](https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#tasks-versus-rootdirect-queries)

**Comment by Kalita-Roman** [comment]
Thank you!
This place in my code didn't like me when I did it. But I didn't know how to make better.
Now I will correct.
